name: Playwright CI

on:
  pull_request:
    branches:
      - main

jobs:
  playwright:
    name: playwright's tests
    runs-on: large

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Install Playwright and dependencies
        run: npx playwright install --with-deps chromium webkit

      - name: Run Playwright tests
        run: npx playwright test --reporter=github

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 3
