name: Playwright CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Create report directory
        run: mkdir -p playwright-report

      - name: Run Playwright tests
        run: yarn playwright test --reporter=json --output=playwright-report/test_result_json.json


      - name: List files in the current directory
        run: |
          echo "Listing files in the current directory:"
          ls -al

      - name: List files in playwright-report directory
        run: |
          echo "Listing files in playwright-report directory:"
          ls -al playwright-report || echo "playwright-report directory does not exist."

      - name: Check directory permissions
        run: |
          echo "Checking permissions for current directory:"
          ls -ld .
          echo "Checking permissions for playwright-report directory:"
          ls -ld playwright-report || echo "playwright-report directory does not exist."

      - name: Verify test result JSON file
        run: |
          filePath="playwright-report/test_result_json.json"
          if [ -f "$filePath" ]; then
            echo "Test result JSON file found."
            ls -l $filePath
          else
            echo "Test result JSON file not found!"
            exit 1
          fi

      - name: Post Playwright test summary
        run: |
          filePath="playwright-report/test_result_json.json"
          if [ ! -f "$filePath" ]; then
            echo "Test result file not found!"
            exit 1
          fi
          PASSED=$(jq '.stats.expected // 0' $filePath)
          FLAKY=$(jq '.stats.flaky // 0' $filePath)
          SKIPPED=$(jq '.stats.skipped // 0' $filePath)
          TOTAL=$((PASSED + FLAKY + SKIPPED))
          SUITES=$(jq '.stats.suites // 0' $filePath)
          DURATION=$(jq '.stats.duration // 0' $filePath)
          DURATION_MIN=$((DURATION / 60000))
          DURATION_SEC=$(((DURATION % 60000) / 1000))
          COMMIT=$(git rev-parse --short HEAD)
          
          echo "**Playwright e2e tests (l: guest p: qGRq-zeok-4Arf)**"
          echo "**passed**  $PASSED passed"
          echo "**flaky**  $FLAKY flaky"
          echo "**skipped**  $SKIPPED skipped"
          echo "### Details"
          echo "**report**  [Open report](playwright-report/index.html) ↗︎"
          echo "**stats**  $TOTAL tests across $SUITES suites"
          echo "**duration**  $DURATION_MIN minutes, $DURATION_SEC seconds"
          echo "**commit**  $COMMIT"
