name: Playwright CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Install Playwright browsers
        run: yarn playwright install --with-deps

      - name: Run Playwright tests with JSON reporter
        run: |
          PLAYWRIGHT_JSON_OUTPUT_NAME=results.json npx playwright test --reporter=json
          ls -l results.json

      - name: Upload test result JSON file
        uses: actions/upload-artifact@v3
        with:
          name: test-results-json
          path: results.json

      - name: Post Playwright test summary
        uses: daun/playwright-report-summary@v3
        if: always() # Отправить комментарий в любом случае
        with:
          report-file: 'results.json'
